application: ninjabin-web
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: web/images

- url: /js
  static_dir: web/js

- url: /css
  static_dir: web/css

- url: /fonts
  static_dir: web/fonts

- url: /contacts
  script: web/cgi/contacts.py

- url: /
  static_files: web/index.html
  upload: web/index.html

- url: /(.*)
  static_files: web/index.html
  upload: web/index.html

libraries:
- name: webapp2
  version: "2.5.2"